In [4]:
import numpy as np 
x = np.array([
    [1.0, 0.0, 1.0],
    [0.0, 2.0, 1.0],
    [1.0, 1.0, 0.0]
])
print("Input embeddings (x):")
print(x)

# step 2 
np.random.seed(42)
d_model = x.shape[1]
d_k = 3
WQ = np.random.randn(d_model, d_k)
WK = np.random.randn(d_model, d_k)
WV = np.random.randn(d_model, d_k)

#Step 3
Q = x @ WQ 
K = x @ WK 
V = x @ WV
print("\nQuery(Q) :")
print(Q)
print("\nKey (K) : ")
print(K)
print("\nvalue (V) : ")
print(V)

#step 4 
Scores = Q @ K.T
print("\nAttention Scores : " )
print(Scores)

#step 5
Scalled_Scores = Scores / np.sqrt(d_k)
print("\nScalled Scores : ")
print(Scalled_Scores)

#step 6 
def softmax(x) :
    exp_x = np.exp(x- np.max(x, axis = -1, keepdims = True))
    return exp_x / np.sum(exp_x, axis = -1, keepdims = True)

attention_weights = softmax(Scalled_Scores)
print("\nAttention Weights :")
print(attention_weights)

#Step 7 
attention_output = attention_weights @ V
print("\nFinal Attention output : ")
print(attention_output)


Input embeddings (x):
[[1. 0. 1.]
 [0. 2. 1.]
 [1. 1. 0.]]

Query(Q) :
[[ 2.07592697  0.62917043  0.17821415]
 [ 4.62527253  0.29912798 -0.9377483 ]
 [ 2.01974401 -0.37241768  0.41355158]]

Key (K) : 
[[-0.01972749 -1.47624881 -0.15148242]
 [-0.07836299 -4.83939161 -3.13558833]
 [ 0.78452232 -2.37669794 -2.19064759]]

value (V) : 
[[-1.4524068  -1.30138111  0.31465519]
 [-0.99593533  0.245979   -4.00048995]
 [-1.13380038 -1.3447755   0.04090058]]

Attention Scores : 
[[-0.99676123 -3.76628414 -0.25714143]
 [-0.39077994  1.13034503  4.97196871]
 [ 0.44729089  0.34727429  1.5637128 ]]

Scalled Scores : 
[[-0.57548036 -2.17446516 -0.14846067]
 [-0.2256169   0.652605    2.87056747]
 [ 0.25824351  0.20049891  0.90281   ]]

Attention Weights :
[[0.36565953 0.07390037 0.56044009]
 [0.03918491 0.09430305 0.86651204]
 [0.25980424 0.24522688 0.49496889]]

Final Attention output : 
[[-1.24011357 -1.21135058 -0.1576587 ]
 [-1.13328384 -1.19306209 -0.32948782]
 [-1.18276746 -0.9434057  -0.87903439]